export const siteCopy = {
  en: {
    nav: {
      home: 'Home',
      scan: 'Start Scan',
      how: 'How It Works',
      language: 'Language',
    },
    languages: {
      english: 'English',
      hindi: 'Hindi',
    },
    home: {
      badge: 'Healthcare-first prescription companion',
      title: 'From confusing prescriptions to clear understanding',
      description:
        'MediLens reads prescription images, organizes the medicine plan, and explains it in plain language with Hindi-ready support for families, clinics, and caregivers.',
      supporting: 'Built to feel calm, clinical, and easy to trust on first use.',
      primaryCta: 'Start scan',
      secondaryCta: 'How it works',
      chips: ['Fast scan workflow', 'Hindi-ready interface', 'Private by design'],
      panelTitle: 'A clinical workflow with a human feel',
      panelSubtitle: 'Designed to reduce friction, not add more screens.',
      panelItems: [
        {
          title: 'Capture',
          description: 'Upload a clear prescription photo from phone, desktop, or clinic tablet.',
        },
        {
          title: 'Decode',
          description: 'OCR and medicine structuring turn handwriting into a readable medicine plan.',
        },
        {
          title: 'Explain',
          description: 'Friendly instructions make dosage, timing, and precautions easier to follow.',
        },
        {
          title: 'Listen',
          description: 'Switch the whole experience between English and Hindi with spoken playback.',
        },
      ],
      pillarsHeading: 'What makes it feel different',
      pillarsSubheading: 'More editorial, less template. More clarity, less clutter.',
      pillars: [
        {
          title: 'Quiet by design',
          description: 'Deep clinical surfaces, soft glow accents, and generous spacing create a more premium feel.',
        },
        {
          title: 'Focused on care',
          description: 'The interface highlights medicine understanding, not flashy dashboards or unnecessary widgets.',
        },
        {
          title: 'Readable for everyone',
          description: 'Large type, bilingual text, and high-contrast sections make the product easier to use.',
        },
      ],
      audienceHeading: 'Built for real-world use',
      audienceSubheading: 'Patients, caregivers, pharmacists, and clinics all get a clearer flow.',
      audience: [
        {
          title: 'For patients',
          items: ['Understand the prescription before taking medicine', 'Read instructions in a familiar language', 'Lower the fear of complex handwriting'],
        },
        {
          title: 'For families',
          items: ['Explain medicines to older parents and children', 'Use voice playback when reading is difficult', 'Keep the same clarity across devices'],
        },
        {
          title: 'For clinics',
          items: ['Reduce repeated clarification calls', 'Create a more modern intake experience', 'Support better prescription handoffs'],
        },
      ],
      trustHeading: 'Trust and safety remain visible',
      trustSubheading: 'A healthcare product should feel precise without feeling cold.',
      trust: [
        {
          title: 'Privacy-first flow',
          description: 'Prescriptions are processed in a way that keeps the experience lightweight and respectful of patient data.',
        },
        {
          title: 'Language switching',
          description: 'The interface text changes between English and Hindi while speech playback follows the selected language.',
        },
        {
          title: 'Clinical reminder',
          description: 'The app helps people understand prescriptions, but it does not replace doctors or pharmacists.',
        },
        {
          title: 'Comfortable scale',
          description: 'Layouts use larger cards, wider spacing, and stronger hierarchy so the site feels more substantial.',
        },
      ],
      ctaHeading: 'Ready for a clearer prescription experience?',
      ctaBody: 'Open the scanner, switch languages, and review medicine instructions in a calmer interface.',
      ctaPrimary: 'Open scanner',
      ctaSecondary: 'Explore the flow',
      footer: {
        about: 'MediLens is a prescription clarity platform designed for healthcare communication, not generic automation.',
        featuresTitle: 'Highlights',
        disclaimerTitle: 'Disclaimer',
        features: ['Medical-grade OCR', 'English + Hindi interface', 'Voice playback support', 'Secure by design'],
        disclaimer: 'Always confirm medication decisions with a qualified healthcare professional.',
      },
    },
    analyze: {
      badge: 'Scanner workspace',
      title: 'Bring a prescription into focus',
      description: 'Upload a clear image and let MediLens structure the medication details into a readable care summary.',
      panelTitle: 'A calmer input surface',
      panelBody: 'Designed for quick uploads, confidence, and fewer distractions while the prescription is being processed.',
      uploadTitle: 'Upload your prescription',
      uploadHint: 'Drag and drop or click to choose a file.',
      uploadAction: 'Choose file',
      uploadFormats: 'Supported formats: JPG, PNG, WebP up to 10MB.',
      dropPrompt: 'Drop the prescription here',
      analyze: 'Analyze prescription',
      analyzing: 'Analyzing...',
      reset: 'Reset',
      previewTitle: 'Preview',
      emptyTitle: 'Ready when you are',
      emptyBody: 'Upload a clear prescription image to start the scan.',
      errorPrefix: 'Something went wrong',
      listenTitle: 'Listen to explanation',
      ocrTitle: 'Prescription text',
      resultFields: {
        medicine: 'Medicine',
        dosage: 'Dosage',
        purpose: 'Purpose',
        precautions: 'Precautions',
        confidence: 'Analysis confidence',
        fullExplanation: 'Full explanation',
      },
    },
    howItWorks: {
      badge: 'How it works',
      title: 'A cleaner flow from photo to understanding',
      description: 'MediLens keeps the journey short, readable, and language-aware so the experience feels like a guided care tool.',
      stepsHeading: 'The process',
      benefitsHeading: 'Why it matters',
      noticeTitle: 'Important medical notice',
      noticeBody: 'MediLens is a communication aid, not a replacement for clinical judgment. Always verify medicine decisions with a healthcare professional.',
      cta: 'Open the scanner',
      steps: [
        {
          id: '01',
          title: 'Upload a prescription',
          description: 'Add a prescription photo from any modern device. Clear images create the best reading experience.',
          detail: 'Works well for handwritten, typed, and mixed-format prescriptions.',
        },
        {
          id: '02',
          title: 'Extract the text',
          description: 'OCR identifies medicine names, dosage patterns, and timing cues from the image.',
          detail: 'The interface stays simple while the system handles the heavy lifting.',
        },
        {
          id: '03',
          title: 'Organize the medicine plan',
          description: 'The scan is turned into a structure that is easier to read and explain to others.',
          detail: 'This reduces confusion when instructions are written quickly or in mixed shorthand.',
        },
        {
          id: '04',
          title: 'Explain in plain language',
          description: 'The output highlights what to take, when to take it, and what to watch for.',
          detail: 'The goal is clarity for patients, caregivers, and front-desk staff.',
        },
        {
          id: '05',
          title: 'Read it aloud',
          description: 'Voice playback supports English and Hindi so the summary can be heard as well as read.',
          detail: 'Helpful for older adults, busy caregivers, and low-literacy users.',
        },
        {
          id: '06',
          title: 'Keep the data respectful',
          description: 'The product is designed around privacy, trust, and a lightweight experience.',
          detail: 'It is meant to support healthcare conversations, not replace them.',
        },
      ],
      benefits: [
        { title: 'Less confusion', desc: 'A structured summary makes prescriptions easier to follow.' },
        { title: 'More confidence', desc: 'Language switching and voice playback reduce friction for families.' },
        { title: 'Better workflow', desc: 'Clinics can present a more modern and understandable experience.' },
        { title: 'More accessible', desc: 'Bilingual content helps bridge literacy and language gaps.' },
      ],
    },
    voice: {
      play: 'Play explanation',
      stop: 'Stop playback',
      speaking: 'Speaking...',
      english: 'English',
      hindi: 'Hindi',
    },
  },
  hi: {
    nav: {
      home: 'मुख्य पृष्ठ',
      scan: 'स्कैन शुरू करें',
      how: 'कैसे काम करता है',
      language: 'भाषा',
    },
    languages: {
      english: 'English',
      hindi: 'हिन्दी',
    },
    home: {
      badge: 'स्वास्थ्य-केंद्रित प्रिस्क्रिप्शन साथी',
      title: 'उलझी हुई दवाओं की पर्ची से साफ़ समझ तक',
      description:
        'MediLens पर्ची की तस्वीर पढ़कर दवाओं की जानकारी को व्यवस्थित करता है और परिवारों, क्लीनिकों और देखभाल करने वालों के लिए सरल हिंदी-सक्षम समझ देता है।',
      supporting: 'शांत, भरोसेमंद और क्लिनिकल महसूस होने वाला अनुभव।',
      primaryCta: 'स्कैन शुरू करें',
      secondaryCta: 'कैसे काम करता है',
      chips: ['तेज़ स्कैन वर्कफ़्लो', 'हिंदी-सक्षम इंटरफ़ेस', 'गोपनीयता-केंद्रित डिज़ाइन'],
      panelTitle: 'मानवीय एहसास वाला क्लिनिकल वर्कफ़्लो',
      panelSubtitle: 'कम रुकावट, कम स्क्रीन, ज्यादा स्पष्टता।',
      panelItems: [
        {
          title: 'कैप्चर',
          description: 'फोन, डेस्कटॉप या क्लिनिक टैबलेट से पर्ची की साफ़ फोटो अपलोड करें।',
        },
        {
          title: 'डिकोड',
          description: 'OCR और संरचना हस्तलिखित पर्ची को पढ़ने योग्य दवा योजना में बदलते हैं।',
        },
        {
          title: 'समझाएँ',
          description: 'सरल निर्देश खुराक, समय और सावधानियों को समझना आसान बनाते हैं।',
        },
        {
          title: 'सुनें',
          description: 'पूरे अनुभव को अंग्रेज़ी और हिंदी के बीच बदलकर आवाज़ में सुनें।',
        },
      ],
      pillarsHeading: 'इसे अलग महसूस कराने वाली बातें',
      pillarsSubheading: 'टेम्पलेट जैसा नहीं, संपादकीय और अधिक प्रीमियम अनुभव।',
      pillars: [
        {
          title: 'शांत डिज़ाइन',
          description: 'गहरे क्लिनिकल सतह, मुलायम ग्लो और खुली spacing इसे ज्यादा प्रीमियम बनाते हैं।',
        },
        {
          title: 'देखभाल पर फोकस',
          description: 'इंटरफ़ेस अनावश्यक विजेट्स की जगह दवा समझ पर ध्यान देता है।',
        },
        {
          title: 'सबके लिए पढ़ने योग्य',
          description: 'बड़ी टाइपोग्राफी, द्विभाषी टेक्स्ट और उच्च कंट्रास्ट उपयोग को आसान बनाते हैं।',
        },
      ],
      audienceHeading: 'वास्तविक उपयोग के लिए बना',
      audienceSubheading: 'मरीज़, परिवार, फ़ार्मासिस्ट और क्लिनिक सभी को साफ़ प्रवाह मिलता है।',
      audience: [
        {
          title: 'मरीज़ों के लिए',
          items: ['दवा लेने से पहले पर्ची समझें', 'अपनी भाषा में निर्देश पढ़ें', 'जटिल लिखावट का डर कम हो'],
        },
        {
          title: 'परिवारों के लिए',
          items: ['बुज़ुर्ग माता-पिता और बच्चों को दवाएँ समझाएँ', 'पढ़ना मुश्किल हो तो आवाज़ सुनें', 'हर डिवाइस पर समान स्पष्टता पाएँ'],
        },
        {
          title: 'क्लिनिकों के लिए',
          items: ['बार-बार clarification कॉल कम करें', 'आधुनिक intake अनुभव दें', 'बेहतर prescription handoff बनाएं'],
        },
      ],
      trustHeading: 'भरोसा और सुरक्षा दिखाई देती है',
      trustSubheading: 'स्वास्थ्य उत्पाद को सटीक भी लगना चाहिए और मानवीय भी।',
      trust: [
        {
          title: 'गोपनीयता-प्रथम प्रवाह',
          description: 'पर्चियों को हल्के और सम्मानजनक अनुभव के साथ प्रोसेस किया जाता है।',
        },
        {
          title: 'भाषा बदलना',
          description: 'इंटरफ़ेस टेक्स्ट हिंदी और अंग्रेज़ी में बदलता है और आवाज़ भी उसी भाषा के अनुसार चलती है।',
        },
        {
          title: 'क्लिनिकल याद दिलाना',
          description: 'यह ऐप दवा समझने में मदद करता है, डॉक्टर या फ़ार्मासिस्ट का विकल्प नहीं है।',
        },
        {
          title: 'आरामदायक स्केल',
          description: 'बड़े कार्ड, ज्यादा spacing और मज़बूत hierarchy इसे अधिक substantial बनाते हैं।',
        },
      ],
      ctaHeading: 'क्या आप पर्ची का अधिक साफ़ अनुभव चाहते हैं?',
      ctaBody: 'स्कैनर खोलें, भाषा बदलें, और शांत इंटरफ़ेस में दवा निर्देश देखें।',
      ctaPrimary: 'स्कैनर खोलें',
      ctaSecondary: 'प्रवाह देखें',
      footer: {
        about: 'MediLens स्वास्थ्य संवाद के लिए बनाया गया प्रिस्क्रिप्शन क्लैरिटी प्लेटफ़ॉर्म है।',
        featuresTitle: 'मुख्य विशेषताएं',
        disclaimerTitle: 'अस्वीकरण',
        features: ['मेडिकल-ग्रेड OCR', 'अंग्रेज़ी + हिंदी इंटरफ़ेस', 'वॉयस प्लेबैक सपोर्ट', 'गोपनीयता-केंद्रित डिज़ाइन'],
        disclaimer: 'कृपया दवा से जुड़े निर्णय योग्य स्वास्थ्य पेशेवर से ज़रूर सत्यापित करें।',
      },
    },
    analyze: {
      badge: 'स्कैनर कार्यक्षेत्र',
      title: 'पर्ची को साफ़ फोकस में लाएँ',
      description: 'एक साफ़ तस्वीर अपलोड करें और MediLens दवा की जानकारी को पढ़ने योग्य सारांश में बदलेगा।',
      panelTitle: 'एक शांत इनपुट सतह',
      panelBody: 'तेज़ अपलोड, भरोसा और कम distraction के लिए तैयार।',
      uploadTitle: 'अपनी पर्ची अपलोड करें',
      uploadHint: 'ड्रैग करें या क्लिक करके फ़ाइल चुनें।',
      uploadAction: 'फ़ाइल चुनें',
      uploadFormats: 'समर्थित फ़ॉर्मेट: JPG, PNG, WebP, 10MB तक।',
      dropPrompt: 'पर्ची यहाँ छोड़ें',
      analyze: 'पर्ची विश्लेषण करें',
      analyzing: 'विश्लेषण हो रहा है...',
      reset: 'रीसेट',
      previewTitle: 'पूर्वावलोकन',
      emptyTitle: 'तैयार होने पर शुरू करें',
      emptyBody: 'शुरू करने के लिए पर्ची की साफ़ तस्वीर अपलोड करें।',
      errorPrefix: 'कुछ गलत हो गया',
      listenTitle: 'व्याख्या सुनें',
      ocrTitle: 'पर्ची टेक्स्ट',
      resultFields: {
        medicine: 'दवा',
        dosage: 'खुराक',
        purpose: 'उद्देश्य',
        precautions: 'सावधानियाँ',
        confidence: 'विश्लेषण भरोसा',
        fullExplanation: 'पूरा विवरण',
      },
    },
    howItWorks: {
      badge: 'कैसे काम करता है',
      title: 'फोटो से समझ तक एक साफ़ प्रवाह',
      description: 'MediLens यात्रा को छोटा, पढ़ने योग्य और भाषा-सचेत रखता है ताकि अनुभव एक guided care tool जैसा लगे।',
      stepsHeading: 'प्रक्रिया',
      benefitsHeading: 'यह क्यों महत्वपूर्ण है',
      noticeTitle: 'महत्वपूर्ण चिकित्सा सूचना',
      noticeBody: 'MediLens एक communication aid है, clinical judgment का विकल्प नहीं। कृपया दवा संबंधी निर्णय हमेशा योग्य स्वास्थ्य पेशेवर से सत्यापित करें।',
      cta: 'स्कैनर खोलें',
      steps: [
        {
          id: '01',
          title: 'पर्ची अपलोड करें',
          description: 'किसी भी आधुनिक डिवाइस से पर्ची की फोटो जोड़ें। साफ़ तस्वीरें सबसे अच्छा अनुभव देती हैं।',
          detail: 'हस्तलिखित, टाइप और mixed-format पर्चियों के लिए उपयुक्त।',
        },
        {
          id: '02',
          title: 'टेक्स्ट निकालें',
          description: 'OCR दवा के नाम, खुराक और समय संकेतों को पहचानता है।',
          detail: 'इंटरफ़ेस सरल रहता है जबकि सिस्टम भारी काम संभालता है।',
        },
        {
          id: '03',
          title: 'दवा योजना व्यवस्थित करें',
          description: 'स्कैन को ऐसी संरचना में बदला जाता है जिसे पढ़ना और समझाना आसान हो।',
          detail: 'तेज़ी से लिखी या shorthand पर्चियों में भ्रम कम होता है।',
        },
        {
          id: '04',
          title: 'सरल भाषा में समझाएँ',
          description: 'आउटपुट में क्या लेना है, कब लेना है और क्या देखना है, यह स्पष्ट होता है।',
          detail: 'लक्ष्य मरीज़, परिवार और फ्रंट-डेस्क स्टाफ के लिए स्पष्टता है।',
        },
        {
          id: '05',
          title: 'आवाज़ में सुनें',
          description: 'English और Hindi voice playback सारांश को पढ़ने के साथ सुनने भी देता है।',
          detail: 'वरिष्ठ नागरिक, व्यस्त देखभालकर्ता और कम literacy वाले उपयोगकर्ताओं के लिए मददगार।',
        },
        {
          id: '06',
          title: 'डेटा का सम्मान करें',
          description: 'उत्पाद privacy, trust और हल्के अनुभव के लिए बनाया गया है।',
          detail: 'यह healthcare conversation का समर्थन करता है, उसे replace नहीं करता।',
        },
      ],
      benefits: [
        { title: 'कम भ्रम', desc: 'संरचित summary पर्ची को समझना आसान बनाती है।' },
        { title: 'ज्यादा भरोसा', desc: 'भाषा switching और voice playback परिवारों की friction कम करते हैं।' },
        { title: 'बेहतर workflow', desc: 'क्लिनिक अधिक आधुनिक और समझने योग्य अनुभव दे सकते हैं।' },
        { title: 'अधिक सुलभ', desc: 'द्विभाषी content भाषा और literacy के अंतर को कम करता है।' },
      ],
    },
    voice: {
      play: 'व्याख्या सुनें',
      stop: 'प्लेबैक रोकें',
      speaking: 'बोल रहा है...',
      english: 'English',
      hindi: 'हिन्दी',
    },
  },
}

export const getSiteCopy = (language) => siteCopy[language] ?? siteCopy.en